# Generated by Django 5.1.6 on 2025-03-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_price',
        ),
    ]
