# Generated by Django 5.1.6 on 2025-03-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availibility',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=100, null=True),
        ),
    ]
